### ISSUE TITLE
Unintended Uploads Permanently Saved

### ISSUE THREAD

**Issue by justin7674** [richardgirges/express-fileupload#102]
Whenever you have a post page (REGARDLESS of whether or not it is built to handle files) and you send a file to it, the file will be uploaded to the server and stay for an unspecified time. For example if I had built a POST request to login users from their credentials, a person could simply write a new request sending a file and the server will save that file even though the page was intended for logging users in and not uploading a file.

**Comment by justin7674** [comment]
I have to execute this snippet of code on every page request otherwise I am left vulnerable to having my server filled with useless data.

```
handlefiles: function(req,res,next){
		const files = req.files || {};
		function cleanupFiles () {
			res.removeListener('finish', cleanupFiles);
			res.removeListener('close', cleanupFiles);
			const files = req.files || {};
			for(var fn in files){
				 fs.unlinkSync(files[fn].path);
			}
		}
		res.on('finish', cleanupFiles);
		res.on('close', cleanupFiles);
		next();
	},
```

**Comment by r3wt** [comment]
how are you attaching the plugin middleware to handle file uploads? sounds like you are handling it as a global middleware rather than as a route level middleware. either way, manual cleanup is required when working with this library in my experience. you can use the tmp package and copy and delete all files, and they will be gc'd at some, similar. i have an example of this i can dig up if you would like it.

as an aside, in your example you are blocking the main thread when you call `fs.unlinkSync()`. use `fs.unlink()` instead to avoid performance issues related to blocking the main thread.

On Oct 23, 2018 2:15 AM, justin7674 <notifications@github.com> wrote:

I have to execute this snippet of code on every page request otherwise I am left vulnerable to having my server filled with useless data.

handlefiles: function(req,res,next){
                const files = req.files || {};
                function cleanupFiles () {
                        res.removeListener('finish', cleanupFiles);
                        res.removeListener('close', cleanupFiles);
                        const files = req.files || {};
                        for(var fn in files){
                                 fs.unlinkSync(files[fn].path);
                        }
                }
                res.on('finish', cleanupFiles);
                res.on('close', cleanupFiles);
                next();
        },

**Comment by justin7674** [comment]
This is the code I am using to instantiate.

	app.use(fileUpload({
		limits: { 
			fileSize: 1 * 1024 * 1024,
			fields: 50,
			files: 1,
			parts: 51,
		}
	}));


How should I use it for route specific cases?

**Comment by RomanBurunkov** [comment]
Hi @justin7674 ,

I believe you should specify routes in the use method:

app.use('this/is/my/upload/route', fileUpload({......

**Comment by r3wt** [comment]
As roman mentioned, you can do it with `app.use()`, however you should be able to add it as top level middleware in express-map-2 as well. depending on your use case it may be simpler to just stick with `app.use()` but below is roughly how to use middleware with `app.map()`(it also supports an array of mixed string/function handlers)

```js	
	var middleware = function middleware(req,res,next){next()};
	var test13Result = app.map('/books',middleware,{
		'GET /books-2': 'books.list',
		'GET /books-2/:id': 'books.loadOne',
		'DELETE /books-2/:id': 'books.delete',
		'PUT /books-2/:id': 'books.update',
		'POST /books-2': 'books.create'
	});
```

**Comment by richardgirges** [comment]
I'm a little confused because this library is built to upload files _into memory_. Nothing is supposed to get placed on the file system until you intentionally use the `.mv` method. 

Can anyone give me some more details on this behavior? Are you seeing uploaded files end up in the `/tmp` directory or something to that effect?

**Comment by justin7674** [comment]
Correct, in this case the tmp directory for my server is the root directory of the server.

**Comment by richardgirges** [comment]
Great, thanks @justin7674 !
