### ISSUE TITLE
Show warning when md5 and tempFileMode are used together

### ISSUE THREAD

**Issue by NiciusB** [richardgirges/express-fileupload#123]
Hey! As mentioned in the documentation, md5 does not work when tempFileMode is used.

While support for it could be added in the future, right now calling md5 with tempFileMode returns a hash of something(?) without any warnings.
This can create confusion, especially is someone didn't read the warning on the docs

**Comment by RomanBurunkov** [comment]
In case of tempfileMode it currenlty returns md5 of empty buffer.

Need to create method to compute md5 with support of large files without huge memory consuption.
Like it did in md5-file module. Or just add md5-file to dependancies and use it in case of tempfileMode;)

**Comment by NiciusB** [comment]
If @richardgirges is fine with it, I'll create a pull request to use md5-file

**Comment by RomanBurunkov** [comment]
Hi @NiciusB , since data handlers works with buffers, I think the better way is to add md5 calculation into data handlers(both temp and in memory), by using 

const hash = crypto.createHash('md5')

and method hash.update(buffer.slice(0, bytesRead)), like it did in that module.

And in fileFactory instead of returning a function for md5, return already calculated md5 hash.

**Comment by RomanBurunkov** [comment]
md5 now works for both options: in memory and tempFile.
