### ISSUE TITLE
EACCES error

### ISSUE THREAD

**Issue by BevilaquaBruno** [richardgirges/express-fileupload#128]
When i try to use `file.mv()`:
```json
{
 "error": {
   "errno":-13, 
   "code":"EACCES",
   "syscall":"rename",
   "path":"/tmp/tmp1552332077101",
   "dest":"./static/img1552332077102.jpg"
 }
}
```
I am using the version `^1.1.2-alpha.1`
I do not know if this is a bug or a permission denied, but i can not fix it.

My app.use():
```javascript
app.use(fileUpload({useTempFiles: true, tempFileDir:'./temp/'}));
```

My code:
```javascript
var a = timestamp();
 req.files.arquivo.mv('./static/img'+a+'.jpg', function (err) {
   if (err)
     //show the EACCES error !!!!!!
     return res.json({'error': err});
 });
```

**Comment by RomanBurunkov** [comment]
Hi @BevilaquaBruno ,

That is wired, could you please check and confirm that you are using the following options:

`{useTempFiles: true, tempFileDir:'./temp/'}`

 when getting this error:

`{
 "error": {
   "errno":-13, 
   "code":"EACCES",
   "syscall":"rename",
   "path":"/tmp/tmp1552332077101",
   "dest":"./static/img1552332077102.jpg"
 }
}`

Asking that because I see different paths: tempFileDir:'./temp/' and "path":"/tmp/tmp1552332077101".

In case of tempFileDir:'./temp/' that should be something like "path":"./temp/tmp1552332077101" or a full path to your temporary folder.

If so, try to use full path instead of relative path.

**Comment by RomanBurunkov** [comment]
My main suggestion that you should use absolute path when setting tempFileDir.

**Comment by BevilaquaBruno** [comment]
I am using `/temp` in my temporary folder.
When i use the absolute path i get a different error:
```
 {
   Error: EACCES: permission denied, 
   open '/var/www/html/tesseract_ocr/temp/tmp1552387746306'
   errno: -13,
   code: 'EACCES',
   syscall: 'open',
   path: '/var/www/html/tesseract_ocr/temp/tmp1552387746306' 
}
```
Now i think this is a permission error

**Comment by BevilaquaBruno** [comment]
I fix it giving the permission with `sudo chown -R MY_USER /temp` and `sudo chown -R MY_USER /static` .
So thank you for the help !
