### ISSUE TITLE
Is it possible to restrict filetypes?

### ISSUE THREAD

**Issue by msankar1991** [richardgirges/express-fileupload#25]
Currently working REST API for uploading the documents to user profile. Is there anyway to restrict the file types to upload. For example png, jpg, jpeg, pdf need to accept from client side?

**Comment by pronein** [comment]
I would do this in two different places.
1. On your server-side express controller handler, verify the file type and reject it if it is invalid. This can be done by checking the actual file contents or simply checking the file type (though the latter could be potentially dangerous due to trust issues).
2. (optional) If you have a client-side front-end where the user selects the file to upload, I would have validation there as well to prevent them from even reaching your API. I make the assumption users do not want to upload a file only to find out that the file is of an invalid type. Better to fail early than process the upload and reject (where possible).

This module seems to be a very straight forward (though I admittedly have not yet looked through the code) module with a single responsibility. Get `file` from `point-a` to `point-b`. Everything else is left to the implementer: validation; error handling; multi-file uploads; etc.

**Comment by richardgirges** [comment]
As @pronein stated, this is something you'd want to do outside of the context of this library.

express-fileupload strives to provide a simple API for uploading files with minimal dependencies. How you'd want to restrict file types is entirely up to you.
