### ISSUE TITLE
how to print the error when using .mv

### ISSUE THREAD

**Issue by prtome** [richardgirges/express-fileupload#38]
I would like (now that everything is working perfectly) manage the errors.
I have the following code, which (purposely) does not work. i am trying to get the error message, but I never get the IAM HERE printed in the log, and of course no message is sent back. 

SORRY - I don't know how to delete this issue.  Brain meltdown due to the heat - everything works as expected

**Comment by richardgirges** [comment]
No worries :)

**Comment by dlazzy** [comment]
Hello,

I'm reopening this issue because I think I forgot something to pass in **.mv()** function. Everything works, but the http POST stuck pending because nothing is returned. Here the `console.log('here')` is never shown in console :

```js
router.post('/upload/img', (req, res) => {
  if (Object.keys(req.files).length == 0) {
    return res.status(400).send('No files were uploaded.');
  }
  let file = req.files.upload_file;

  file.mv(__dirname + '/../../public/imgs/articles/' + file.name), (err) => {
    if (err)
      return res.status(500).send(err);

    res.send('File uploaded!');
  };
});
```

Even with the output produced by the **morgan** package I don't see the call, but the file is created in the right folder :thinking: Thanks for you help
