### ISSUE TITLE
Restify?

### ISSUE THREAD

**Issue by lanzosuarez** [richardgirges/express-fileupload#46]
Will this work on restify? or this library is limited with express?

**Comment by richardgirges** [comment]
Hey @lanzosuarez, it actually might work with restify considering restify is based on [connect](https://www.npmjs.com/package/connect). But it's not officially supported since none of the unit tests in this library use restify.

If you'd like to present official restify to this library, feel free to send a PR with some unit tests!

**Comment by richardgirges** [comment]
Closing this issue, but please let me know if you would like to re-open a discussion around restify support
