### ISSUE TITLE
How do I access the busboy object?

### ISSUE THREAD

**Issue by mwilde345** [richardgirges/express-fileupload#68]
I read up on connect-busboy but I can't access that as explained via req.busboy or req.Busboy.
My goal is to access the event handlers within.

**Comment by richardgirges** [comment]
I'm not exposing the busboy object from express-fileupload. Primarily because I don't want to create a user-facing dependency on busboy that will disable me from removing busboy from this package down the line.

I think it would be a much safer alternative for you to use connect-busboy directly, or fork this package if you'd like to alter it to expose busboy - I can help point you in the area of the code where you can do that.

Apologies for any inconvenience this may cause!

**Comment by lakshaygaur** [comment]
@mwilde345 @richardgirges Please provide any details if you were able to integrate busboy with express-fileupload.
I'm trying to put some constraints on file mimetype ... So any suggestion is welcomed as well.

**Comment by mwilde345** [comment]
@lakshaygaur I ended up not using express-fileupload. I am uploading my file using ajax xhr. On the server side I use busboy directly and filter the file size.
`var busboy = new Busboy({
        headers: req.headers,
        limits: {
            fileSize: 3 * 1024 * 1024
        }
    });`

You could use that format to filter the file type I believe.

**Comment by lakshaygaur** [comment]
@mwilde345 Thanks for the suggestion. But i just used a function instead to upload all my files. I'm able to put constraints there.
